# Generated by Django 5.0.6 on 2024-05-19 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='profile',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
